name: default

on:
  push:
    branches:
      - '*'

jobs:
  tests_e2e:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Generate report
        run: npm run report
      - name: Create folder
        run: mkdir downloads
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber_report
          path: downloads
